name: Build And Run Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Format
        run: ./tools/format.sh --dry-run

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Build
        run: ./tools/build.sh --compiler g++-14 --compile-tests

      - name: Test
        run: ./build/tests/rusty_iterators_tests
